---
# tasks file for mariadb
#

- name: Disable SELinux
  selinux:
    state: disabled

<<<<<<< HEAD
- name: Open MariaDB port on firewalld
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled
  notify: 
    - restart_firewalld

- name: Reboot host
  reboot:

=======
>>>>>>> 134736d84881d8416eca3c3f0f64d8d920b408c5
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install mariadb
  yum:
    name: 
      - mariadb-server
      - python2-PyMySQL
    state: latest

<<<<<<< HEAD
=======
- name: Open MariaDB port on firewalld
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled
  notify: 
    - restart_firewalld

>>>>>>> 134736d84881d8416eca3c3f0f64d8d920b408c5
- name: Start and enable mariadb service
  service:
    name: mariadb
    state: started
    enabled: true

- name: MariaDB client file
  copy:
    dest: /root/.my.cnf
    content: |
      [client]
      user=root
      password=""

