---
- name: use mariadb role playbook
  hosts: 192.168.5.176
  become: true

  pre_tasks:
    - debug:
        msg: 'Beginning db server configuration.'

  roles:
    - role: mariadb

  post_tasks:
    - debug:
        msg: 'Db server has been configured.'


- name: use httpd_php role playbook
  hosts: 192.168.5.177
  become: true

  pre_tasks:
    - debug:
        msg: 'Beginning web server configuration.'

  roles:
    - role: httpd_php

  post_tasks:
    - debug:
        msg: 'Web server has been configured.'

