---
- name: use nginx role playbook
  hosts: web 
  become: true

  pre_tasks:
    - debug:
        msg: 'Beginning web server configuration.'

  roles:
    - role: httpd_php

  post_tasks:
    - debug:
        msg: 'Web server has been configured.'
