---
# tasks file for httpd_php
#

- name: Disable SELinux
  selinux:
    state: disabled

- name: Install httpd
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - httpd
    - php
    - php-mysql

- name: Start and enable httpd service
  service:
    name: httpd
    state: started
    enabled: true

- name: Open HTTP port on firewalld
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  notify:
    - restart_firewalld

- name: Remove default httpd site
  file: 
    path: "{{ httpd_dir }}/conf.d/welcome.conf" 
    state: absent

- name: Create website root folders
  file: 
    path: "{{ sites_root }}/{{ item.name }}/html/"
    state: directory
    mode: 755
  with_items: "{{ projects }}"

- name: Copy application files
  template:
    src: "templates/{{ item.src }}"
    dest: "{{ sites_root }}/app-salaire/html/{{ item.dest }}"
  loop:
    - { src: "create_db.php.j2", dest: "create_db.php" }
    - { src: "create_table.php.j2", dest: "create_table.php" }
    - { src: "getting_data.php.j2", dest: "getting_data.php" }
    - { src: "insert_data.php.j2", dest: "insert_data.php" }
    - { src: "remove_data.php.j2", dest: "remove_data.php" }
    - { src: "remove_db.php.j2", dest: "remove_db.php" }

- name: Setup httpd folders
  file: 
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ httpd_dir }}/sites-available"
    - "{{ httpd_dir }}/sites-enabled"

- name: Setup httpd server conf
  template:
    src: templates/httpd.conf.j2
    dest: "{{ httpd_dir }}/conf/httpd.conf"

- name: Setup vhost
  template:
    src: templates/vhost.conf.j2 
    dest: "{{ httpd_dir }}/sites-available/{{ item.name }}.conf"
  with_items: "{{ projects }}"

#- name: Setup website content
#  template: 
#    src: templates/index.html.j2 
#    dest: "{{ sites_root }}/{{ item.name }}/html/index.html"
#  with_items: "{{ projects }}"

#- name: Create folders for sites and upstreams
#  file: 
#    path: "{{ nginx_dir }}/sites"
#    state: directory

- name: Create symlinks for sites-enabled
  file: 
    state: link 
    src: "{{ httpd_dir }}/sites-available/{{ item.name }}.conf"
    dest: "{{ httpd_dir }}/sites-enabled/{{ item.name }}.conf"
  with_items: "{{ projects }}"

- name: Restart httpd
  service:
    name: httpd
    state: restarted
